studentportal/api/urls.py
from django.urls import path
from api import views
 
app_name='api'

urlpatterns = [
    #USER APIS START
    path('get-user-object/<int:pk>',views.get_userdata,name='get-admin-object'),
    path('get-cashiers/',views.get_cashier,name="get-cashiers"),
    path('get-registrars/',views.get_registrar,name="get-registrars"),
    path('get-teachers/',views.get_teacher,name="get-teachers"),
    path('get-students/',views.get_student,name="get-students"),
    
    
    
    #USER APIS END
    
    #NEWS API START
    path('get-news/',views.news_list,name='news-list'),
    path('get-news-page/',views.get_news,name='news-page'),
    path('get-news-object/<int:pk>',views.get_news_object,name='get_news_object'),
    #NEWS API END
    
    #GRADES API START
    path('get-grades/',views.get_grades,name='grade-list'),
    path('get-grade-object/<int:pk>',views.get_specific_grade,name='get-grade-object'),
    #GRADES API END

    #TRANSACTION API START
    path('get-payment-data/<int:pk>',views.get_payment_data,name='get-payment-data'),
    path('get-transaction-page-unconfirmed/',views.cashier_transaction_data_unconfirmed,name='cashier-transaction-unconfirmed'),
    path('get-transaction-page-confirmed/',views.cashier_transaction_data_confirmed,name='cashier-transaction-confirmed'),
    path('get-registrar-transaction-page/',views.registrar_doc_list,name='registrar-doc-list'),
    path('get-registrar-complete-page/',views.registrar_complete_list,name='registrar-complete-list'),
    path('export-transaction-report/',views.export_transaction,name="export-transaction"),
    path('student-transaction-history/',views.student_transaction_list,name="student-transaction-history"),
    #TRANSACTION API END

    #NOTIFS START
    path('notifications/',views.get_notifs,name="get-notifs"),
    path('notifications/mark-read/',views.mark_notifs_read,name="mark-notifs"),
    path('notifications/clear-notifs/',views.clear_notifs,name="clear-notifs"),


    #NOTIFS END


]

studentportal/authentication/urls.py
from django.urls import path, include, reverse_lazy
from authentication import views
from django.contrib.auth import views as auth_views

app_name = 'authentication'

urlpatterns = [
    path('', views.home, name='login'),
    path('auth-regular-user/',views.login_regular_user, name='log-reg-user'),
    path('auth-admin-user/',views.login_admin, name='log-admin'),
    path('logout',views.logout_user,name='logout'),
    path('401',views.unauthorized_view, name='unauthorized-view'),

    #PASSWORD RESET LINKS
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html', email_template_name='registration/password_reset_email.html', success_url=reverse_lazy('authentication:password_reset_done')), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('authentication:password_reset_complete')), name="password_reset_confirm"),
    path('reset_success/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    #PASSWORD RESET LINKS
    
    #MIDDLEWARE BS START
    path('first-login-password/', views.first_log_password  , name='first-login-password'),
    #MIDDLEWARE BS END


    # EMAIL SENT
     path('email-sent/', views.email_sent, name='email-sent'),

     path('set-new-pass/', views.set_new_pass, name='set-new-pass'),

     path('pass-success/', views.pass_success, name='pass-success'),

]

studentportal/home/urls.py
from django.urls import path, include
from home import views

app_name = 'home'

urlpatterns = [
    #CASHIER URLS START =========================

    path('cashier/', views.cashier_home, name='cashier-home'),
    path('cashier/edit-cashier', views.edit_cashier, name='edit-cashier'),
    path('cashier/edit-cashier-password', views.edit_cashier_password, name='edit-cashier-password'),
    path('cashier/unconfirmed-transactions',views.unconfirmed_transaction_cashier,name='unconfirmed-cashier-transactions'),
    path('cashier/confirmed-transactions',views.confirmed_transaction_cashier,name='confirmed-cashier-transactions'),

    #CASHIER URLS END=============================

    #REGISTRAR URLS START ========================
    path('registrar/', views.registrar_dashboard, name='registrar-dashboard'),
    path('registrar/document-request/', views.registrar_document_request, name='document-request'),
    path('registrar/completed-request/', views.registrar_document_complete, name='complete-document'),
    path('registrar/generate-document/', views.registrar_generate_document, name='generate-document'),
    path('registrar/grade-list/', views.registrar_grade_list, name='grade-list'),
    path('registrar/gen-cert/', views.generate_cert, name='generate-cert'),
    path('registrar/gen-cert-success/', views.gen_cert_success, name='generate-cert-success'),
    path('registrar/edit-registrar', views.edit_registrar, name='edit-registrar'),
    path('registrar/edit-registrar-password', views.edit_registrar_password, name='edit-registrar-password'),
    path('registrar/create-student/', views.registrar_create_student, name='create-student-profile'),
    path('registrar/upload-grades/',views.registrar_upload_grades,name='upload-grades'),





    #REGISTRAR URLS END ========================

    #TEACHER URLS START ========================
    
    path('teacher/',views.teacher_home,name='teacher-home'),
    path('teacher/newsfeed',views.teacher_newsfeed,name='teacher-newsfeed'),
    path('teacher/edit-teacher',views.edit_teacher,name='teacher-edit'),
    path('teacher/edit-teacher-password',views.edit_teacher_password,name='teacher-edit-password'),

    #TEACHER URLS END   ========================

    #STUDENT URLS START ========================

    path('student/',views.student_home,name='student-home'),
    path('student/profile',views.student_profile,name='student-profile'),
    path('student/password-change',views.student_edit_password,name='student-password'),
    path('student/request-form',views.student_requestform,name='student-request-form'),
    path('student/newsfeed',views.student_newsfeed,name='student-newsfeed'),
    path('student/transaction-history',views.student_transaction,name='student-transaction'),

    #STUDENT URLS END ========================
    
    path('announcement/', include('news.urls',namespace='news')),
    path('transactions/',include('transactions.urls',namespace='transactions')),
    path('user/',include('users.urls',namespace='users')),
    path('grade-management/',include('grades.urls',namespace='grades'))

]

studentportal/studentportal/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', include('authentication.urls', namespace='authentication')),
    path('admin/', include('admin.urls',namespace='admin')),
    path('home/',include('home.urls', namespace='home')),
    path('api/',include('api.urls', namespace='api')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

if settings.DEBUG:
    urlpatterns+= staticfiles_urlpatterns()
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentportal/home/models.py
from django.db import models


# Create your models here.

# @ALDEN ADD A MODEL FOR PROGRAMS/COURSES AND THEIR SUBJECTS TOO 

studentportal/home/forms.py
from django import forms

studentportal/home/views.py
import os
import pandas as pd
import datetime
from weasyprint import HTML
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.template.loader import render_to_string
from news.models import Announcement
from transactions import forms, models
from users.forms import edit_user, change_password, StudentProfileUpdate, StudentUserUpdate
from users.models import CustomUser, Student
from notifications.models import Notification
from grades.models import Grades
from django.core.mail import send_mail
from django.conf import settings

# Create your views here.

#CASHIER VIEWS START =============================

@login_required(login_url='authentication:login')
def cashier_home(request):
    if request.user.role != 'CASHIER':
        return redirect('authentication:unauthorized-view')
    transactions = models.Transaction.objects.order_by("-date_time").filter(is_confirmed=True)[:6]
    unconfirmed_transactions = models.Transaction.objects.filter(is_confirmed=False).count()
    form = forms.manualTransactionAdd()

    context = {
        'transactions': transactions,
        'unconfirmed_transactions':unconfirmed_transactions,
        'form': form
    }
    return render(request, 'cashier/dashboard.html', context)

@login_required(login_url='authentication:login')
def unconfirmed_transaction_cashier(request):
    if request.user.role != 'CASHIER':
        return redirect('authentication:unauthorized-view')
    form = forms.updatePayment()
    context = {
        'form': form
    }
    return render(request, 'cashier/unconfirmed-transactions.html', context)


@login_required(login_url='authentication:login')
def confirmed_transaction_cashier(request):
    if request.user.role != 'CASHIER':
        return redirect('authentication:unauthorized-view')
    return render(request, 'cashier/confirmed-transaction.html')

@login_required(login_url='authentication:login')
def edit_cashier(request):
    if request.user.role != 'CASHIER':
        return redirect('authentication:unauthorized-view')
    form = edit_user(instance=request.user)
    context = {
        'form':form
    }
    return render(request,'cashier/edit-cashier.html',context)

def edit_cashier_password(request):
    if request.user.role != 'CASHIER':
        return redirect('authentication:unauthorized-view')
    form = change_password(request.user)
    context={
        'form':form
    }
    return render(request,'cashier/edit-cashier-password.html', context)

#CASHIER VIEWS END =============================


#REGISTRAR VIEWS START=================================

@login_required(login_url='authentication:login')
def registrar_home(request):
    if request.user.role != 'REGISTRAR':
        return redirect('authentication:unauthorized-view')
    return render(request, 'registrar/registrar.html')

@login_required(login_url='authentication:login')
def registrar_dashboard(request):
    if request.user.role != 'REGISTRAR':
        return redirect('authentication:unauthorized-view')
    total_students = Student.student.count()
    pending_transactions = models.Transaction.objects.filter(
        registrar_status=models.Transaction.RegistrarStatus.PENDING,
        payment_purpose__in=[
            models.Transaction.PaymentPurposeChoice.CERT_GRADES,
            models.Transaction.PaymentPurposeChoice.CERT_MORALE,
            models.Transaction.PaymentPurposeChoice.CERT_ENROL,
            models.Transaction.PaymentPurposeChoice.TRANS_RECORD
        ], is_confirmed=True
    ).count()
    ready_transactions = models.Transaction.objects.filter(
        registrar_status=models.Transaction.RegistrarStatus.COMPLETE,
        payment_purpose__in=[
            models.Transaction.PaymentPurposeChoice.CERT_GRADES,
            models.Transaction.PaymentPurposeChoice.CERT_MORALE,
            models.Transaction.PaymentPurposeChoice.CERT_ENROL,
            models.Transaction.PaymentPurposeChoice.TRANS_RECORD
        ], is_confirmed=True
    ).count()

    pending_transaction_list = models.Transaction.objects.filter(
        registrar_status__in=[
            models.Transaction.RegistrarStatus.PENDING,
            models.Transaction.RegistrarStatus.AVAILABLE,
            ],
        payment_purpose__in=[
            models.Transaction.PaymentPurposeChoice.CERT_GRADES,
            models.Transaction.PaymentPurposeChoice.CERT_MORALE,
            models.Transaction.PaymentPurposeChoice.CERT_ENROL,
            models.Transaction.PaymentPurposeChoice.TRANS_RECORD
        ], is_confirmed=True
    ).order_by('-date_time')[:5]

    context = {
        'total_students': total_students,
        'pending_transactions':pending_transactions,
        'ready_transactions':ready_transactions,
        'transactions':pending_transaction_list 
    }
    
    return render(request, 'registrar/registrar-dashboard.html',context)

@login_required(login_url='authentication:login')
def edit_registrar(request):
    if request.user.role != 'REGISTRAR':
        return redirect('authentication:unauthorized-view')
    form = edit_user(instance=request.user)
    context = {
        'form':form
    }
    return render(request,'registrar/edit-registrar.html',context)

@login_required(login_url='authentication:login')
def edit_registrar_password(request):
    if request.user.role != 'REGISTRAR':
        return redirect('authentication:unauthorized-view')
    form = change_password(request.user)
    context={
        'form':form
    }
    return render(request,'registrar/edit-registrar-password.html', context)

@login_required(login_url='authentication:login')
def registrar_document_request(request):
    if request.user.role != 'REGISTRAR':
        return redirect('authentication:unauthorized-view')
    if request.GET.get("success") == "1":
        messages.success(request, "Certificate has been successfully downloaded.")
    return render(request, 'registrar/document-request.html')

@login_required(login_url='authentication:login')
def registrar_document_complete(request):
    if request.user.role != 'REGISTRAR':
        return redirect('authentication:unauthorized-view')
    return render(request, 'registrar/document-list-complete.html')

@login_required(login_url='authentication:login')
def registrar_generate_document(request):
    if request.GET.get("success") == "1":
        messages.success(request, "Certificate has been successfully downloaded.")

    if request.user.role != 'REGISTRAR':
        return redirect('authentication:unauthorized-view')
    return render(request, 'registrar/generate-document.html')

@login_required(login_url='authentication:login')
def registrar_create_student(request):
    if request.user.role != 'REGISTRAR':
        return redirect('authentication:unauthorized-view')
    return render(request,'registrar/create-student-profile.html')

@login_required(login_url='authentication:login')
def registrar_grade_list(request):
    if request.user.role != 'REGISTRAR':
        return redirect('authentication:unauthorized-view')
    return render(request,'registrar/registrar-student-grades.html')


@login_required(login_url='authentication:login')
def registrar_upload_grades(request):
    if request.user.role != 'REGISTRAR':
        return redirect('authentication:unauthorized-view')
    
    return render(request,'registrar/registrar-upload-grades.html')





#REGISTRAR VIEWS END  =================================

#STUDENT VIEWS START ==================================
@login_required(login_url='authentication:login')
def student_home(request):
    if request.user.role != 'STUDENT':
        return redirect('authentication:unauthorized-view')
    return render(request,'studentview/studentdashboard.html')

@login_required(login_url='authentication:login')
def student_profile(request):
    if request.user.role != 'STUDENT':
        return redirect('authentication:unauthorized-view')
    u_form = StudentUserUpdate(instance=request.user)
    p_form = StudentProfileUpdate(instance=request.user.student_id)
    context = {
            'u_form': u_form,
            'p_form': p_form,
            
        }

    return render(request,'studentview/studentprofile.html',context)

@login_required(login_url='authentication:login')
def student_edit_password(request):
    if request.user.role != 'STUDENT':
        return redirect('authentication:unauthorized-view')
    form = change_password(request.user)
    context={
        'form':form
    }
    return render(request,'studentview/studentchangepassword.html', context)


@login_required(login_url='authentication:login')
def student_requestform(request):
    if request.user.role != 'STUDENT':
        return redirect('authentication:unauthorized-view')
    form = forms.StudentPaymentForm()
    context = {
        'form':form
    }
    return render(request,'studentview/studentrequestform.html',context)

@login_required(login_url='authentication:login')
def student_newsfeed(request):
    if request.user.role != 'STUDENT':
        return redirect('authentication:unauthorized-view')
    return render(request,'studentview/newsfeed.html')

@login_required(login_url='authentication:login')
def student_transaction(request):
    if request.user.role != 'STUDENT':
        return redirect('authentication:unauthorized-view')
    return render(request, 'studentview/transaction-history.html')

#STUDENT VIEWS END   ==================================

#TEACHER VIEWS START   ==================================

#TEACHER VIEWS START   ==================================


@login_required(login_url='authentication:login')
def teacher_home(request):
    if request.user.role != 'TEACHER':
        return redirect('authentication:unauthorized-view')
    
    return render(request,'teacherview/teacherdashboard.html')

studentportal/home/templates/registrar/document-list-complete.html
{% extends "registrar/registrar_sidebar.html" %}
{% block title %}
Completed Document Requests
{% endblock title %}

{%load static%}
{% block content %}
{%for msg in messages%}
  {%if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <span>{{msg}}</span>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
  {%elif msg.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
       <div class="alert alert-warnings alert-dismissible fade show" role="alert">
      <span>{{msg}}</span>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {%endif%}
{%endfor%}



<div class="registrar-crud-dashboard">
        <h1 class="registrar-list-title">Complete Request List</h1>

        <div class="filter-docu-request">
            <select id="filter-request">
                <option value="">Display All</option>
                <option value="CERTIFICATE OF ENROLLMENT">Certificate of Enrollment</option>
                <option value="CERTIFICATE OF GOOD MORALE">Certificate of Good Morale</option>
                <option value="CERTIFICATE OF GRADES">Certificate of Grades</option>
            </select>
        </div>
    
        <!-- Search Section -->
        <div class="registrar-search-container">
            <input type="text" id="registrar-search-request" placeholder="Search Requests">
            <button type="button" class="button-req-search" id="searchButton">Search</button>
        </div>
    
        <!-- Document Request Table -->
        <table class="request-table unique-request-table">
            <thead class="registrar-table-head">
                <tr>
                    <th class="registrar-table-header">Student USN</th>
                    <th class="registrar-table-header">Student Name</th>
                    <th class="registrar-table-header">Document Type</th>
                    <th class="registrar-table-header">Request Date</th>
                    <th class="registrar-table-header">Status</th>
                </tr>
            </thead>
            <tbody id="request-list" class="request-list">
             
            </tbody>
        </table>
    
        <!-- Pagination -->
        <div id="registrar-pagination">
          
        </div>
    </div>

     <!-- Process Request Modal -->
     <div class="modal fade req-document-modal" id="processRequest" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog req-document-dialog">
          <div class="modal-content req-document-content">
              <div class="modal-header req-document-header">
                  <h5 class="modal-title req-document-title" id="exampleModalLabel">Request Details</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body req-document-body">
                  <form id="certificate-form" action="{%url 'home:generate-cert'%}" method="post">
                      {% csrf_token %}
                      <input type="hidden" name="transID" id="transID">
                      <div class="container req-document-container">
                          <div class="row req-document-row">
                              <div class="col req-document-col">
                                  <h4>Transaction Information</h4>
                                  <div class="form-group req-document-group">
                                      <label for="student-usn">Student USN:</label>
                                      <input type="text" name="student" id="student-usn" readonly>
                                  </div>
                                  <div class="form-group req-document-group">
                                      <label for="student-name">Student Name:</label>
                                      <input type="text" name="student-name" id="student-name" disabled>
                                  </div>
                                  <div class="form-group req-document-group">
                                      <label for="doc-type">Document Type:</label>
                                      <input type="text" name="document_type" id="document-type" readonly>
                                  </div>
                                  <div class="form-group req-document-group">
                                      <label for="date-requested">Date Requested:</label>
                                      <input type="text" name="date-requested" id="date-requested" disabled>
                                  </div>
                              </div>
                              <div class="col cert-morale-enrollment req-document-cert">
                                  <h6>Enter Year and Semester (If Certificate of Grades, enter previous semester)</h6>
                                  <label for="semester">Semester:</label>
                                  <select name="semester" id="semester">
                                      <option value="1st">1st</option>
                                      <option value="2nd">2nd</option>
                                  </select>
                                  <label for="year">School Year:</label>
                                  <input type="text" name="year" id="school-year" placeholder="Enter School Year (example: 2024-2025)">
                                  <label for="pickup-date">Set Pick-up Date:</label>
                                  <input type="date" name="pickup-date" id="pickup-date">
                              </div>
                          </div>
                      </div>
              </div>
              <div class="modal-footer req-document-footer">
                  <button type="button" class="btn btn-secondary" id="process-request-closed" data-bs-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-primary process-request" id="process-request">Process Requests</button>
                  </form>
              </div>
          </div>
      </div>
  </div>
  

      <!-- APPROVED MODAL SECTION  -->

      <div class="modal fade approved-request-modal" id="approveRequest" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header approved-request-header">
              <h5 class="modal-title" id="exampleModalLabel">Approved Request</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
            <form action="{%url 'home:transactions:complete-request'%}" method="post">
            {% csrf_token %}
              <div class="doc-request-message">
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary approved-request-closed" data-bs-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary complete-request  approved-request-complete">Complete Document Request</button>
            </form>
            </div>
          </div>
        </div>
      </div>

<script src="{%static 'js/registrar-docu-complete.js'%}"></script>

{% endblock content %}

studentportal/home/templates/registrar/document-success.html
{% extends "registrar/registrar_sidebar.html" %}
{% block title %}
Document Generation Success
{% endblock title %}

{%load static%}
{% block content %}

<div class="successful-created">
  <div class="successful">
    <p>Document has successfully been created, an email has been sent to the student.</p>
  </div>
</div>

{% endblock content %}

studentportal/home/templates/registrar/registrar_sidebar.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
    <link rel="icon" href="{%static 'favicon/favicon.ico'%}" />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      rel="stylesheet"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'styles/sidebar.css'%}" />
    
    <link rel="stylesheet" href="{% static 'styles/registrar.css'%}" />

    <link rel="stylesheet" href="{% static 'styles/registrar-dashboard.css'%}" />

    <link rel="stylesheet" href="{% static 'styles/document-request.css'%}" />
    <link rel="stylesheet" href="{% static 'styles/alert-styles.css'%}" />
    <link rel="stylesheet" href="{% static 'styles/generate-document.css'%}" />
    <link rel="stylesheet" href="{% static 'styles/create-student-profile.css'%}" />
    <link rel="stylesheet" href="{% static 'styles/edit-cashier.css'%}" />
    <link rel="stylesheet" href="{% static 'styles/registrar-upload-grades.css'%}">

    <link rel="stylesheet" href="{% static 'styles/edit-registrar.css'%}" />

    <link rel="stylesheet" href="{% static 'styles/succesful-created.css'%}" />

    <script src="{% static 'js/registrar-dashboard.js'%}"></script>

    <script src="{% static 'js/create-student.js'%}"></script>

  </head>
  <body>
    <!-- Sidebar -->
    <div id="sidebar" class="sidebar">
      <div class="sidebar-header">
        <img
          src="{% static 'images/LOGO-VA.2.png'%}"
          alt="VA Logo"
          class="aclc-logo"
        />
        <span class="aclc-apalit">Vision Academy</span>
      </div>
      <ul class="sidebar-menu">
        <li>
          <a
            href="{%url 'home:registrar-dashboard'%}"
            class="menu-item"
            data-link="dashboard"
            ><i class="fas fa-house-user"></i> Dashboard</a
          >
        </li>

        <li class="dropdown">
          <a href="#" class="menu-item dropdown-toggle" data-toggle="dropdown"
            ><i class="fas fa-file-alt"></i> Document Requests
            <span class="caret"></span
          ></a>
          <ul class="dropdown-menu">

            <li><a href="{%url 'home:document-request'%}">View Pending/Available Pending Requests</a></li>
            <li><a href="{%url 'home:complete-document'%}">View Completed Requests</a></li>
            
          </ul>
        </li>

        <li>
          <a
            href="{%url 'home:grade-list'%}"
            class="menu-item"
            data-link="dashboard"
            ><i class="fas fa-edit"></i>View Grades</a
          >
        </li>

        <li>
          <a href="{%url 'home:create-student-profile'%}" class="menu-item" data-link="create-student-profile">
           <i class="fas fa-user-plus"></i> Create Student Users
          </a>
        </li>
        
        <li>
          <a href="{%url 'home:edit-registrar'%}" class="menu-item" data-link="edit-users">
            <i class="fas fa-user-edit"></i> Edit User
          </a>
        </li>

      </ul>
      <div class="user-profile">
        <a href="{%url 'home:edit-registrar-password'%}" class="menu-item" data-link="profile">
          <i class="fas fa-key"></i> Change Password
        </a>

    
        <a href="{%url 'authentication:logout'%}" class="menu-item logout"
          ><i class="fas fa-sign-out-alt"></i> Logout</a
        >
      </div>
    </div>

    <!-- Main content -->
    <div class="content">
      <button id="toggle-btn" class="toggle-btn">☰</button>
      <button id="close-btn" class="close-btn">×</button>
{% block content %} {% endblock content %}

    <footer class="txn-footer">
      &copy; 2025 Transaction Management System. All rights reserved.
    </footer>
    </div>

    <script src="{% static 'js/sidebar.js'%}"></script>
  </body>
</html>