studentportal/api/urls.py
from django.urls import path
from api import views
 
app_name='api'

urlpatterns = [
    #USER APIS START
    path('get-user-object/<int:pk>',views.get_userdata,name='get-admin-object'),
    path('get-cashiers/',views.get_cashier,name="get-cashiers"),
    path('get-registrars/',views.get_registrar,name="get-registrars"),
    path('get-teachers/',views.get_teacher,name="get-teachers"),
    path('get-students/',views.get_student,name="get-students"),
    
    
    
    #USER APIS END
    
    #NEWS API START
    path('get-news/',views.news_list,name='news-list'),
    path('get-news-page/',views.get_news,name='news-page'),
    path('get-news-object/<int:pk>',views.get_news_object,name='get_news_object'),
    #NEWS API END
    
    #GRADES API START
    path('get-grades/',views.get_grades,name='grade-list'),
    path('get-grade-object/<int:pk>',views.get_specific_grade,name='get-grade-object'),
    #GRADES API END

    #TRANSACTION API START
    path('get-payment-data/<int:pk>',views.get_payment_data,name='get-payment-data'),
    path('get-transaction-page-unconfirmed/',views.cashier_transaction_data_unconfirmed,name='cashier-transaction-unconfirmed'),
    path('get-transaction-page-confirmed/',views.cashier_transaction_data_confirmed,name='cashier-transaction-confirmed'),
    path('get-registrar-transaction-page/',views.registrar_doc_list,name='registrar-doc-list'),
    path('get-registrar-complete-page/',views.registrar_complete_list,name='registrar-complete-list'),
    path('export-transaction-report/',views.export_transaction,name="export-transaction"),
    path('student-transaction-history/',views.student_transaction_list,name="student-transaction-history"),
    #TRANSACTION API END

    #NOTIFS START
    path('notifications/',views.get_notifs,name="get-notifs"),
    path('notifications/mark-read/',views.mark_notifs_read,name="mark-notifs"),
    path('notifications/clear-notifs/',views.clear_notifs,name="clear-notifs"),


    #NOTIFS END


]

studentportal/authentication/urls.py
from django.urls import path, include, reverse_lazy
from authentication import views
from django.contrib.auth import views as auth_views

app_name = 'authentication'

urlpatterns = [
    path('', views.home, name='login'),
    path('auth-regular-user/',views.login_regular_user, name='log-reg-user'),
    path('auth-admin-user/',views.login_admin, name='log-admin'),
    path('logout',views.logout_user,name='logout'),
    path('401',views.unauthorized_view, name='unauthorized-view'),

    #PASSWORD RESET LINKS
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html', email_template_name='registration/password_reset_email.html', success_url=reverse_lazy('authentication:password_reset_done')), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('authentication:password_reset_complete')), name="password_reset_confirm"),
    path('reset_success/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    #PASSWORD RESET LINKS
    
    #MIDDLEWARE BS START
    path('first-login-password/', views.first_log_password  , name='first-login-password'),
    #MIDDLEWARE BS END


    # EMAIL SENT
     path('email-sent/', views.email_sent, name='email-sent'),

     path('set-new-pass/', views.set_new_pass, name='set-new-pass'),

     path('pass-success/', views.pass_success, name='pass-success'),

]

studentportal/studentportal/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', include('authentication.urls', namespace='authentication')),
    path('admin/', include('admin.urls',namespace='admin')),
    path('home/',include('home.urls', namespace='home')),
    path('api/',include('api.urls', namespace='api')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

if settings.DEBUG:
    urlpatterns+= staticfiles_urlpatterns()
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentportal/admin/templates/login/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vision Academy Admin Login Page</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles/login.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="icon" href="{% static 'favicon/favicon.ico' %}">
</head>
<body>

    <div class="login-container">
        <!-- Left section with image -->
        <div class="left-section"></div>

        <!-- Right section with login form -->
        <div class="right-section">
            <div class="login-frame">
                <img src="{% static 'images/LOGO-VA.png' %}" alt="VA Logo"> <!-- Replace with your logo -->
                <p class="login-title"><strong>ADMIN LOGIN</strong></p>

                <!-- Error Message Container -->
                {%for msg in messages %}
                <div id="loginAlertContainer" class="login-alert-container">
                    <div id="loginAlertMessage" class="login-alert login-alert-danger">
                        {{msg}}
                    </div>
                </div>
         {%endfor%}
                <form method="post" action="{%url 'authentication:log-admin'%}" id="loginForm">
                    {% csrf_token %} 
                    <input type="text" class="form-control" id="username" placeholder="USN" name="username" required>

                    <!-- Password field with show/hide toggle -->
                    <div class="password-container">
                        <input type="password" class="form-control" id="password" placeholder="Password" name="password" required>
                    </div>
                    

                    <button type="submit" class="btn btn-block btn-login">Log In</button>
                </form>
                <a href="{%url 'authentication:reset_password'%}" class="forgot-password">Forgot password?</a>
            </div>
        </div>
    </div>


</body>
</html>