studentportal/admin/urls.py
from django.urls import path, include
from admin import views as views_admin

app_name = 'admin'
urlpatterns = [
    path('', views_admin.admin_login, name='admin-login'),
    path('home/', views_admin.home, name='dashboard'),
    path('edit-admin/',views_admin.edit_admin_user,name='edit-admin'),
    path('edit-admin-password',views_admin.edit_admin_password,name='edit-admin-password'),
    path('newsfeed-list',views_admin.admin_newsfeed,name='admin-newsfeed'),
    path('newsfeed-edit',views_admin.edit_news_item,name='edit-news'),
    path('newsfeed-delete',views_admin.delete_news_item,name='delete-news'),
    path('usermanagement/', include('users.urls', namespace='usermanagement')),
    path('transactionmanagement/',include('transactions.urls', namespace='transactions'))
]

studentportal/api/urls.py
from django.urls import path
from api import views
 
app_name='api'

urlpatterns = [
    #USER APIS START
    path('get-user-object/<int:pk>',views.get_userdata,name='get-admin-object'),
    path('get-cashiers/',views.get_cashier,name="get-cashiers"),
    path('get-registrars/',views.get_registrar,name="get-registrars"),
    path('get-teachers/',views.get_teacher,name="get-teachers"),
    path('get-students/',views.get_student,name="get-students"),
    
    
    
    #USER APIS END
    
    #NEWS API START
    path('get-news/',views.news_list,name='news-list'),
    path('get-news-page/',views.get_news,name='news-page'),
    path('get-news-object/<int:pk>',views.get_news_object,name='get_news_object'),
    #NEWS API END
    
    #GRADES API START
    path('get-grades/',views.get_grades,name='grade-list'),
    path('get-grade-object/<int:pk>',views.get_specific_grade,name='get-grade-object'),
    #GRADES API END

    #TRANSACTION API START
    path('get-payment-data/<int:pk>',views.get_payment_data,name='get-payment-data'),
    path('get-transaction-page-unconfirmed/',views.cashier_transaction_data_unconfirmed,name='cashier-transaction-unconfirmed'),
    path('get-transaction-page-confirmed/',views.cashier_transaction_data_confirmed,name='cashier-transaction-confirmed'),
    path('get-registrar-transaction-page/',views.registrar_doc_list,name='registrar-doc-list'),
    path('get-registrar-complete-page/',views.registrar_complete_list,name='registrar-complete-list'),
    path('export-transaction-report/',views.export_transaction,name="export-transaction"),
    path('student-transaction-history/',views.student_transaction_list,name="student-transaction-history"),
    #TRANSACTION API END

    #NOTIFS START
    path('notifications/',views.get_notifs,name="get-notifs"),
    path('notifications/mark-read/',views.mark_notifs_read,name="mark-notifs"),
    path('notifications/clear-notifs/',views.clear_notifs,name="clear-notifs"),


    #NOTIFS END


]

studentportal/studentportal/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', include('authentication.urls', namespace='authentication')),
    path('admin/', include('admin.urls',namespace='admin')),
    path('home/',include('home.urls', namespace='home')),
    path('api/',include('api.urls', namespace='api')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

if settings.DEBUG:
    urlpatterns+= staticfiles_urlpatterns()
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentportal/admin/templates/dashboard.html
{% extends "adminbase/base.html" %} {%load static%} {%block title%}Admin
Dashboard{%endblock%} {%block content%}

{%for msg in messages%}
  {%if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <span>{{msg}}</span>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
  {%elif msg.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
       <div class="alert alert-warnings alert-dismissible fade show" role="alert">
      <span>{{msg}}</span>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {%endif%}
{%endfor%}








<div id="container">
  <div class="admin-dashboard">
    <header class="admin-dashboard-header">
      <div class="logo">
        <img src="{% static 'images/LOGO-VA.2.png'%}" alt="ACLC Apalit Logo" />
      </div>
      <h1>Admin Dashboard</h1>
    </header>
    <main class="admin-dashboard-main">
      <section class="actions">
        <h2>Quick Actions</h2>
        <div class="action-cards">
          <div class="card">
            <i class="fa fa-user-plus"></i>
            <h3>Edit Admin User</h3>
            <p>Edit the details of the current admin user</p>
            <a href="{%url 'admin:edit-admin'%}" class="btn">Go</a>
          </div>
          <div class="card">
            <i class="fa fa-edit"></i>
            <h3>View Registrar Users</h3>
            <p>Manage accounts for registrars.</p>
            <a href="{%url 'admin:users:registrar-list'%}" class="btn">Go</a>
          </div>
          <div class="card">
            <i class="fa fa-book"></i>
            <h3>View Student Users</h3>
            <p>Manage accounts for students</p>
            <a href="{%url 'admin:users:student-list'%}" class="btn">Go</a>
          </div>
        </div>
      </section>

      <section class="form-section">
        <h2>Create a New User</h2>
        <form
          id="quick-action"
          action="{%url 'admin:users:dashboard-action'%}"
          method="POST"
        >
          <div class="form-group">
            <label for="userType">User Type</label>
            {% csrf_token %}
            <select id="userType" name="user_type" required>
              <option value="" disabled selected>Select User type</option>
              <option value="TEACHER">Teacher</option>
              <option value="STUDENT">Student</option>
              <option value="REGISTRAR">Registrar</option>
              <option value="CASHIER">Cashier</option>
            </select>
          </div>
          <div class="form-group">
            <label for="first_name">First Name:</label>
            <input
              type="text"
              id="first_name"
              name="first_name"
              required
              placeholder="Enter First Name"
            />
          </div>
          <div class="form-group">
            <label for="last_name">Last Name:</label>
            <input
              type="text"
              id="last_name"
              name="last_name"
              required
              placeholder="Enter Last Name"
            />
          </div>
          <div class="form-group">
            <label id="username_label" for="userName">Username:</label>
            <input
              type="text"
              id="userName"
              name="username"
              required
              placeholder="Enter username"
            />
          </div>

          <div class="form-group">
            <label for="email">Email</label>
            <input
              type="email"
              id="email"
              name="email"
              required
              placeholder="Enter email"
            />
          </div>

          <div class="form-group">
            <label for="password">Assigned Password</label>
            <input
              type="text"
              id="password"
              name="password"
              required
              placeholder="Password generated here"
              readonly
            />
          </div>
           <div class="form-group" id="course_input">
            <label for="course">Course</label>
            <input
              type="text"
              id="course-field"
              name="course"
              placeholder="Enter course"
            />
          </div>
          <button type="submit" class="submit-btn">Create User</button>
        </form>
      </section>
    </main>
  </div>
</div>

<script src="{%static 'js/admin_dashboard.js'%}"></script>
{%endblock%}

studentportal/admin/templates/editadmin-password.html
{% extends "adminbase/base.html" %}
{% block title %} Edit Admin Password 
{%endblock title %}
{% block content %}
{%for msg in messages%}
  {%if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    <div class="alert alert-warnings alert-dismissible fade show" role="alert">
      <span>{{msg}}</span>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
  {%elif msg.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
       <div class="alert alert-warnings alert-dismissible fade show" role="alert">
      <span>{{msg}}</span>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {%endif%}
{%endfor%}

<div class="edit-pass">

  <div class="container">
    <h1>Edit Admin Password</h1>
    <div class="row">
      <form action="{%url 'admin:users:change-password'%}" method="post">
        {% csrf_token %}
      <div class="col">
        <label for="old-password">Old Password</label>
        <div class="form-group">{{form.old_password}}</div>
      </div>
      <div class="col">
        <label for="new-password1">New Password</label>
        <div class="form-group">{{form.new_password1}}</div>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <label for="new-password2">Confirm New Password</label>
        <div class="form-group">{{form.new_password2}}</div>
      </div>
    </div>
    <div class="form-group">
      <button type="submit" class="submit-btn">Update Password</button>
    </form>
    </div>
  </div>
</div>

{% endblock content %}

studentportal/admin/templates/editadmin.html
{% extends "adminbase/base.html" %}
{% block title %}
Edit Admin User
{% endblock title %}

{%load static%}
{% block content %}
{%for msg in messages%}
  {%if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <span>{{msg}}</span>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
  {%elif msg.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
       <div class="alert alert-warnings alert-dismissible fade show" role="alert">
      <span>{{msg}}</span>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {%endif%}
{%endfor%}

<div class="container">
  <h1>Edit Admin User</h1>
  <div class="edit-admin-form">
      <form action="{% url 'admin:users:edit-user' %}" method="POST">
          {% csrf_token %}
          
          <!-- First Name & Last Name Row -->
          <div class="row">
              <div class="col">
                  <div class="test">
                      <label for="first_name">First Name:</label>
                      {{ form.first_name }}
                  </div>
              </div>
              <div class="col">
                  <div class="test">
                      <label for="last_name">Last Name:</label>
                      {{ form.last_name }}
                  </div>
              </div>
          </div>

          <!-- Email & Username Row -->
          <div class="row">
              <div class="col">
                  <div class="test">
                      <label for="email">Email:</label>
                      {{ form.email }}
                  </div>
              </div>
              <div class="col">
                  <div class="test">
                      <label for="username">Username:</label>
                      {{ form.username }}
                  </div>
              </div>
          </div>

          <!-- Save Button (Centered Below) -->
          <button class="save-btn" type="submit">Save Changes</button>
      </form>
  </div>
</div>


{% endblock content %}

studentportal/admin/templates/newsfeed-edit.html
{% extends "adminbase/base.html" %}
{% block title %}
News Feed
{% endblock title %}
{%load static%}
{%block content%}


{%for msg in messages%}
  {%if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <span>{{msg}}</span>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
  {%elif msg.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
       <div class="alert alert-warnings alert-dismissible fade show" role="alert">
      <span>{{msg}}</span>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {%endif%}
{%endfor%}




<!-- Main Content Section -->
<div class="main_content_wrapper">
    <!-- Search Bar -->
    <div class="search_bar_container">
        <input type="text" placeholder="Search announcements..." class="search_announcements" id="search-input">
        <button type="button" class="news-button" id="search-btn">Search</button>
    </div>
  
    <!-- Main Newsfeed Section -->
    <main class="newsfeed-main-container">
        <!-- Dropdown for Filtering Announcements by Teacher -->
        <div class="announcement_category_container">
            <select class="category-dropdown" id="filterDropdown">
                <option value="desc">Most Recent</option>
                <option value="asc">Oldest</option>
            </select>
        </div>
    
        <!-- Newsfeed Section -->
        <div class="newsfeed_announcements_container" id="newsfeed">
      </div>
      <div id="pagination"></div>
    </main>
  </div>

  <!-- MODAL SECTION -->
  <div class="modal fade edit-button-modal" id="edit-newsitem" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit News Item</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{%url 'admin:edit-news'%}" method="post">
        {% csrf_token %}
        <input type="hidden" name="newsID" id="newsID">
        <div class="form-group">
            <label for="title">Title:</label>
            <input type="text" name="title" id="title_edit" required>
            <label for="body">Body:</label>
       <textarea name="body" id="body_edit" cols="30" rows="5">

       </textarea>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
    </form>
      </div>
    </div>
  </div>
</div>

  <div class="modal fade delete-button-modal" id="delete-newsitem" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header delete-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete Confirmation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <form action="{%url 'admin:delete-news'%}" method="post">
      {% csrf_token %}
      <input type="hidden" name="newsID" id="deleteID">
        <p>Delete this news item?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Confirm Delete</button>
      </form>
      </div>
    </div>
  </div>
</div>

<script src="{%static 'js/admin_newsfeed.js'%}"></script>
{% endblock content %}

studentportal/admin/templates/usermanagement.html
{% extends "_base/base.html" %}

{% block content %}
Test
{% endblock content %}